### ISSUE TITLE
Sometimes the app's background becomes white

### ISSUE THREAD

**Issue by elena-zh** [gnosis/ido-ux#343]
Sometimes the app's background becomes white
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/e1b946de-e7e6-4e2e-aa7f-163f4ee3452f)
However, the issue is not reproducible when open the app in an 'incognito' tab (or clear site data).

**Expected**: the app's background should be in deep blue

**Comment by gabitoesmiapodo** [comment]
@josojo are we keeping the light / dark theme functionality?

Removing all that might solve this issue (or otherwise implementing a light theme too).

**Comment by josojo** [comment]
Maybe in much further in the future, we might want to enable it. But I guess not over the coming 3 months.

Were you able to reproduce it? We should first be able to do that. Otherwise, we can not test it even when we remove all the code.

But yeah, once we are able to do that, I am happy with removing some code.

Though overall, this has never been reported by "new user", so I expect it more to be a caching issue in some way... Though I don't know.

**Comment by gabitoesmiapodo** [comment]
Hm, no I couldn't reproduce the issue (and I tried...).

I too suspect it's related to caching, so it's probable that new users won't face this issue.

Anyway, if you are not planning on removing the feature let's just leave alone for now.

**Comment by elena-zh** [comment]
Hi everyone!
I'm still able to open the app in the staging environment with a 'white' background. 
And yes, it must be a cache issue as I definitely remember that I opened this link with an 'old' app design. And it had a 'white' background.
This is the main reason. I think. As I do not have such issues in Dev/Prod env-ts.
![image](https://user-images.githubusercontent.com/70885163/116669078-d188c980-a9a6-11eb-9491-2b0371786914.png)

**Comment by elena-zh** [comment]
closed as the issue is no longer reproducible
