### ISSUE TITLE
4 unnecessary infura call:

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#417]
https://github.com/gnosis/ido-ux/pull/411#issuecomment-813278298

**Comment by josojo** [comment]
Actuaally, its still severe:
![image.png](https://images.zenhubusercontent.com/5ddee9ea1d3e1600010ad960/21797560-8ae4-4bab-b2d5-6e0cff3fa4dc)

**Comment by mariano-aguero** [comment]
I'm going to close this issue. The error returned by the endpoint is due to the infura key being over the limit. This should not happen again since in another PR a validation was added regarding if the user is logged in or not. Also only 1 or 2 requests are made on an auction detail if it is available for claiming. It is not worth spending more time on this, if the infura key is blocked again for having reached the limit, other measures should be taken, for example: add the domain to a white list or others already discussed in the channel

**Comment by mariano-aguero** [comment]
We can see here the request ...
![Screenshot_20210405_143145](https://user-images.githubusercontent.com/1144028/113604853-36f1d080-961c-11eb-94da-54be27355c8e.png)
