### ISSUE TITLE
Warn users in order confirm modal, if their bidding price is below current auction price

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#469]
old text
```
Many users don't understand the system and place orders even right now below the current auction clearing price. The result is that they are spending quite some gas, but they will for sure not buy any tokens.

Please throw an error message, if the auction is in cancelation_not_possible phase and the user is trying to place a bid below the current clearing price.
```
This is already done here:

```
if (
    derivedAuctionInfo?.clearingPriceSellOrder != null &&
    derivedAuctionInfo?.clearingPrice != null &&
    derivedAuctionInfo?.auctioningToken != undefined &&
    derivedAuctionInfo?.biddingToken != undefined &&
    auctionState == AuctionState.ORDER_PLACING &&
    buyAmountScaled &&
    sellAmountScaled
      ?.mul(derivedAuctionInfo?.clearingPriceSellOrder?.buyAmount.raw.toString())
      .lte(
        buyAmountScaled.mul(derivedAuctionInfo?.clearingPriceSellOrder?.sellAmount.raw.toString()),
      )
  ) {
    error =
      error ?? showPricesInverted
        ? 'Price must be lower than ' + derivedAuctionInfo?.clearingPrice?.invert().toSignificant(5)
        : 'Price must be higher than ' + derivedAuctionInfo?.clearingPrice?.toSignificant(5)
  }
  ```
  
  Actual feature request:
  If the auction is in the following state: auctionState == AuctionState.ORDER_PLACING_AND_CANCELING, many users still place an order with a limit price below the clearing price. This will most likely just waste gas, but in some rare cases, this behaviour makes sense. 
  Hence we will not prohibit this behaviour but warn the users.
  
  Expected behaviour:
  if -auctionState == AuctionState.ORDER_PLACING_AND_CANCELING && orderprice < clearing price
  the user should see a warning in here:
  
![image](https://user-images.githubusercontent.com/7348154/117108645-c6a5ae80-ad83-11eb-9b0f-17b099523d9b.png)

Below the information of the order cancellation date, there should be a message:
```
[lock] You are placing an order below the current clearing price. Most likely your order will not succeed in buying <auctionToken.symbol>.
```

 The text needs to be changed to 
 ```
[lock] You are placing an order above the current clearing price. Most likely your order will not succeed in buying <auctionToken.symbol>.
 ```
 if we are in the case that the token prices are inverted.

**Comment by henrypalacios** [comment]
I have problems to reproduce this scenario with the phase **cancelation_not_possible**, I have tried to place a timestamp in the `OrderPlacement` component after assigning [`derivedAuctionInfo`](https://github.com/gnosis/ido-ux/blob/74539912e0240d0e9f06d53a0fce020b41f17b45/src/components/auction/OrderPlacement/index.tsx#L145)
```javascript
derivedAuctionInfo.orderCancellationEndDate = 1620159282
```
I have tested this with **auction=20**, **chainId=4** with `orderCancellationEndDate` (Tuesday, 1 June 2021 4:00:00GMT), but I don't know if it would be enough.

On the other hand I have the auction with **auction=20**, **chainId=4** with `orderCancellationEndDate` = 0. which I not shure if it should be considered as in **cancelation_not_possible** phase since the beginning of the auction.

Lastly, I would like to clarify the expected behavior.
When the auction is in **cancelation_not_possible** phase, If the user tries to place a bid below the current price by clicking on the "**Place Order**" button, a warn message that the order cannot be placed should be displayed.
![Selection_267.png](https://images.zenhubusercontent.com/608ac91261f99497a3047e7b/44ebe104-b71a-4cf2-a9cc-32a276c4dc21)

**Comment by josojo** [comment]
Hi Henry

I am deeply sorry that the task was not well defined. It was an old issue and somehow only the title was adjusted.
Please keep on asking if something makes no sense to you!

Yes, I think your mocking strategy in general works. Though it's not needed. You can test the behaviour on this auction
https://ido-ux.dev.gnosisdev.com/#/auction?auctionId=69&chainId=4#topAnchor
it has a cancellation date in the future and the current clearing price is higher than the minimum price.

Regarding the expected behaviour, hopefully, my edited ticket clarifies the request.
