### ISSUE TITLE
cannot place an order by whitelisted address

### ISSUE THREAD

**Issue by tatyanakurinskaya** [gnosis/ido-ux#601]
1. open gnosis safe, APPS and start an auction using Gnosis Auction Starter w/ whitelisted address 0xd176Effb29f9a80F06db43eCfa4ef428370ed673
2. open Gnosis Auctions app and open just started auction w/ connected metamask account 0xd176Effb29f9a80F06db43eCfa4ef428370ed673

Result: https://images.zenhubusercontent.com/326940559/eafd33ec-9b18-4602-bea6-86b52f4c059c/private_auction_may_20__2021_9_36_pm.mp4
Exp.result: possibility to place an order

**Comment by fedgiac** [comment]
I was able to reproduce the issue on my end. I created a new auction on Rinkeby (<span>#</span>125) and successfully registered the signatures with the scripts. I think this might be a backend issue, since the frontend reads `Signature not available` from the correct backend query. Not sure if it takes time to register new signatures?
CC @josojo.  

<details><summary>Details</summary>

This is the signature I registered:
```
{"auctionId":125,"chainId":4,"allowListContract":"0x7C882F296335734B958b35DA6b2595FA00043AE9","signatures":[{"user":"0xcB1FF0c484a2267E39e19a82A8c313E633C106C6","signature":"0x000000000000000000000000000000000000000000000000000000000000001b39f65ec6e44bc153b653cfd763702e751bf3114fb671f315233242b2af0d102e7a606e027e77b40e61ad60d9b6e5827e2856e39673db4819cdd03d892ff6f8e8"}]}
```
Generated with:
```
$ yarn hardhat generateSignatures --auction-id 125 --network rinkeby --file-with-address /dev/stdin <<<"0xcB1FF0c484a2267E39e19a82A8c313E633C106C6" --post-to-api
yarn run v1.22.10
$ /var/home/federico/gnosis-code/ido-contracts/node_modules/.bin/hardhat generateSignatures --auction-id 125 --network rinkeby --file-with-address /dev/stdin --post-to-api
Using the account:  0xF6C304d3e84b3da892Ef04d3103e3C8187256629  to generate signatures
Creating signatures for the  0 -th package
Dev-Api returned:  All signatures added
Done in 6.27s.
```
This is the request that the frontend makes:
https://ido-v1-api-rinkeby.dev.gnosisdev.com/api/v1/get_signature/125/0xcB1FF0c484a2267E39e19a82A8c313E633C106C6
And this is the current answer of that request:
```
"Signature not available for user 0xcb1f…06c6"
```

It doesn't appear to be an issue of diferent staging/prod environment since both scripts and the link I'm using to participate to the auction ([this](https://ido-ux.staging.gnosisdev.com/#/auction)) use the same backend ([this](https://ido-v1-api-rinkeby.dev.gnosisdev.com/api/v1)).
@josojo, is it expected that the scripts use the `dev` link to post signatures?
</details>

**Comment by fedgiac** [comment]
Sorry for the false alarm, this was indeed because of a mismatch between the dev link and the prod link when creating the signature. The issue is that I was uploading the signatures with `--post-to-api` but checking the dev link at https://ido-ux.dev.gnosisdev.com/ (which uses dev) in order to see Rinkeby transactions.
In this case, I should have used `--post-to-dev-api` instead. After doing that, I could participate to the auction. Not sure if this helps solving the issue in this thread.

**Comment by josojo** [comment]
Improved the documentation here:
https://github.com/gnosis/ido-contracts/pull/126
