### ISSUE TITLE
Granularity feature shows incorrect granularities

### ISSUE THREAD

**Issue by josojo** [gnosis/ido-ux#721]
The current vita-auction is no longer showing the right options of granularity of 0.0..1, but just 1000, 100, ...

**Comment by elena-zh** [comment]
@josojo , I think the root cause of this issue is calculation of the default value in the granularity dropdown: it is calculated as  (MaxPrice-MinPrice)/10. Since we have an order with 1000 price, 100 becomes a default value in the list, and 2 ranges up and down are added there
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/fc731768-10ac-4e99-ba09-608e467b8e26)

So, what is the best option for you to fix this issue
 - add more ranges up and down for the default value
- recalculate somehow a default granularity value?

Thanks
